repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=WebKit, -i]
  - repo: local
    hooks:
      - id: link-platformio
        name: link platformio
        entry: sh scripts/link_platformio.sh
        language: system
      - id: check-platformio
        name: check-platformio
        entry: platformio check --environment native  --environment disco_f407vg --src-filters="-<src/FreeRTOS/**> -<src/System/**>"
        pass_filenames: false
        language: system
      - id: build-platformio
        name: build-platformios
        entry: platformio run --environment native  --environment disco_f407vg
        pass_filenames: false
        language: system
